### ISSUE TITLE
Unable to use with Selenium

### ISSUE THREAD

**Issue by hdoupe** [conda-forge/firefox-feedstock#40]
Issue:

I'm trying to use Bokeh to save a picture of a plot. Under the hood, [Bokeh uses Selenium](https://docs.bokeh.org/en/latest/docs/reference/io.html#bokeh.io.export_png) and the firefox/geckdriver to render the plot in a headless browser and take a screenshot of it. I'm unable to use the firefox and geckodriver packages on the `conda-forge` channel to drive the headless browser.

Do you have any advice on how I should go about this? Thanks in advance for taking a look at this! I've been trying to get this work on and off for a few weeks now. I know it's a thorny problem and maybe out of scope to get this work for the `firefox` feedstock.

Here's a `Dockerfile` I'm using for this:

```dockerfile
FROM continuumio/miniconda3

RUN conda install -c conda-forge selenium "firefox==81.0" geckodriver ipython

RUN echo 'from selenium import webdriver \n\
driver = webdriver.Firefox()' > /test_simple_way.py

# https://github.com/bokeh/bokeh/blob/branch-2.1/bokeh/io/webdriver.py#L55-L60
RUN echo 'from selenium import webdriver \n\
from selenium.webdriver.remote.webdriver import WebDriver \n\
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary \n\
from os.path import devnull \n\

binary = FirefoxBinary("/opt/conda/bin/firefox") \n\
options = webdriver.firefox.options.Options() \n\
options.add_argument("--headless") \n\
wd = webdriver.Firefox(firefox_binary=binary, options=options, service_log_path=devnull) \n\
wd = webdriver.Firefox(firefox_binary="/opt/conda/bin/firefox", options=options, service_log_path=devnull) \n\
' > /test_bokeh_way.py
```

**Test simple script:**

```python
# test_simple_way.py
from selenium import webdriver 
driver = webdriver.Firefox()
```

```python
$ docker run -it tb-selenium python test_simple_way.py
Traceback (most recent call last):
  File "test_simple_way.py", line 2, in <module>
    driver = webdriver.Firefox()
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

```

**Use code from [Bokeh repository](https://github.com/bokeh/bokeh/blob/branch-2.1/bokeh/io/webdriver.py#L55-L60):**

```python
# test_bokeh_way.py
from selenium import webdriver 
from selenium.webdriver.remote.webdriver import WebDriver 
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary 
from os.path import devnull 
binary = FirefoxBinary("/opt/conda/bin/firefox") 
options = webdriver.firefox.options.Options() 
options.add_argument("--headless") 
wd = webdriver.Firefox(firefox_binary=binary, options=options, service_log_path=devnull) 
wd = webdriver.Firefox(firefox_binary="/opt/conda/bin/firefox", options=options, service_log_path=devnull) 
```

```
$ docker run -it tb-selenium python test_bokeh_way.py
Traceback (most recent call last):
  File "test_bokeh_way.py", line 8, in <module>
    wd = webdriver.Firefox(firefox_binary=binary, options=options, service_log_path=devnull) 
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
```

<br/>
Environment (<code>conda list</code>):
<details>

```
(base) root@71fb2d57ee08:/# conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                1.3.0                    py37_0  
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h2e261b9_0  
chardet                   3.0.4                 py37_1003  
conda                     4.8.5            py37hc8dfbb8_1    conda-forge
conda-package-handling    1.6.0            py37h7b6447c_0  
cryptography              2.8              py37h1ba5d50_0  
decorator                 4.4.2                      py_0    conda-forge
firefox                   81.0                 he1b5a44_0    conda-forge
geckodriver               0.27.0               he1b5a44_0    conda-forge
idna                      2.8                      py37_0  
ipython                   7.18.1           py37hc6149b9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.2                   py37_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.2                  he6710b0_0  
openssl                   1.1.1h               h516909a_0    conda-forge
parso                     0.5.2                      py_0  
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pip                       20.0.2                   py37_1  
prompt-toolkit            3.0.7                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycosat                   0.6.3            py37h7b6447c_0  
pycparser                 2.19                     py37_0  
pygments                  2.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                   py37_0  
pysocks                   1.7.1                    py37_0  
python                    3.7.6                h0371630_2  
python_abi                3.7                     1_cp37m    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py37_1  
ruamel_yaml               0.15.87          py37h7b6447c_0  
selenium                  3.141.0         py37h8f50634_1001    conda-forge
setuptools                45.2.0                   py37_0  
six                       1.14.0                   py37_0  
sqlite                    3.31.1               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tqdm                      4.42.1                     py_0  
traitlets                 5.0.4                      py_1    conda-forge
urllib3                   1.25.8                   py37_0  
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.34.2                   py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
(base) root@71fb2d57ee08:/# conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.28
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.22.0 CPython/3.7.6 Linux/5.4.0-48-generic debian/10 glibc/2.28
                UID:GID : 0:0
             netrc file : None
           offline mode : False

(base) root@71fb2d57ee08:/# 


```
</details>

**Comment by bollwyvl** [comment]
Sorry for the inconvenience, thanks for filling out the full report! 

This is due to a change in how `geckodriver 0.27.0` validates the binary. This feedstock makes a `$PREFIX/bin/firefox` wrapper bash script which invokes the real `firefox`.  Firefox ships a _lot_ of files that want to be in particular places relative to each other.

Today, the options are:
- easy: pin to `geckodriver =0.26.0`
  - it's not _that_ broken, haven't played with the PDF output, which was one of the marquee features
- less easy: add `$PREFIX/bin/FirefoxApp` to `$PATH` (depends on platform) when testing
- harder: detect and change the arguments to selenium
  - e.g. https://github.com/conda-forge/firefox-feedstock/blob/master/recipe/test_selenium.py#L33
  - some helpful "wrappers" make it hard to pass this kind of information in

In the future, we should investigate using a symlink to avoid this headache...

**Comment by hdoupe** [comment]
Hey @bollwyvl, thanks for the quick response. I'm perfectly happy to go the easy way and pin to `0.26.0` for now. I updated the Dockerfile:

```dockerfile
FROM continuumio/miniconda3

RUN conda install -c conda-forge selenium "firefox==81.0" "geckodriver==0.26.0" ipython

RUN echo 'from selenium import webdriver \n\
driver = webdriver.Firefox()' > /test_simple_way.py

# https://github.com/bokeh/bokeh/blob/branch-2.1/bokeh/io/webdriver.py#L55-L60
RUN echo 'from selenium import webdriver \n\
from selenium.webdriver.remote.webdriver import WebDriver \n\
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary \n\
from os.path import devnull \n\

binary = FirefoxBinary("/opt/conda/bin/firefox") \n\
options = webdriver.firefox.options.Options() \n\
options.add_argument("--headless") \n\
wd = webdriver.Firefox(firefox_binary=binary, options=options, service_log_path=devnull) \n\
wd = webdriver.Firefox(firefox_binary="/opt/conda/bin/firefox", options=options, service_log_path=devnull) \n\
' > /test_bokeh_way.py
```

And got these results:

```
(taxbrain-dev) ~/Tax-Brain 
$ docker run -it tb-selenium python test_bokeh_way.py
Traceback (most recent call last):
  File "test_bokeh_way.py", line 8, in <module>
    wd = webdriver.Firefox(firefox_binary=binary, options=options, service_log_path=devnull) 
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

(taxbrain-dev) ~/Tax-Brain 
$ docker run -it tb-selenium python test_simple_way.py
Traceback (most recent call last):
  File "test_simple_way.py", line 2, in <module>
    driver = webdriver.Firefox()
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

```

It looks like the bokeh script is now producing the same error message as the simple script. Previously:

```
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
```

Now:

```
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

Do you have any ideas what may be happening? Do I need to actually install Firefox in the Docker image?

**Comment by bollwyvl** [comment]
> `Unable to find a matching set`

This means firefox crashed. You can crank up the verbosity of geckodriver (`--log-level TRACE`), but here's my hunch:

Yeah, even though it's "headless" it still needs a fair amount of heavy-duty stuff.

Having "a" modern firefox on your machine will usually be enough, as it will bring along all of the [gtk and x11 deps](https://github.com/conda-forge/firefox-feedstock/blob/master/recipe/yum_requirements.txt) you need.  At that point, one might just use a system firefox, no?! However, being able to pin (or at least track) the versions of `firefox & geckodriver & selenium` together is useful, I find.

**Comment by hdoupe** [comment]
Ah, that makes sense. Thanks for all of the help and info @bollwyvl! I talked with my colleague and he's going to look into some other approaches that don't use a headless browser.

> a fair amount of heavy-duty stuff.

Understood. I tried to install chrome in a docker image and oh my:

![Screenshot from 2020-10-05 11-15-30](https://user-images.githubusercontent.com/9206065/95098196-5c992e00-06fc-11eb-9ba3-1bd91d98a182.png)

**Comment by hdoupe** [comment]
Closing since my colleague and I are going a different direction. Thanks again for your time @bollwyvl !

**Comment by bollwyvl** [comment]
Much like a real computer (vs docker/VMs), sure: a real browser can be overkill unless you are _testing whether something works in a real browser_. If you just want pictures, just about anything else will be more maintainable over time. Good luck with whatever you're doing!

If you do end up needing it: the advantage of the firefox/geckodriver stack:
- LTS exists (e.g. `68` and `78`)
  - good luck with any version of chrome that isn't bleeding-edge-today (it might upgrade itself while you're testing)
  - what even is safari? 
- geckodriver vs firefox compatibility has a _useful_, published support window
  - chromedriver needs an exact version of chrome these days, down to the build level... not the same version string as itself, of course!

**Comment by bollwyvl** [comment]
For any others that come along: [geckodriver 0.28.0](https://github.com/conda-forge/geckodriver-feedstock/pull/16) is no longer so hard-core about only starting a Real Firefox Binary:

> Firefox can be started again via a shell script that is located outside of the Firefox directory on Linux
> - https://github.com/mozilla/geckodriver/releases/tag/v0.28.0
